name: Apple Music New Releases

on:
  schedule:
    - cron: '10 12 * * *' # Every day at 12:10 UTC (China time 20:10) for new releases (runs after LookApp)
  workflow_dispatch: # Allow manual trigger

# External services disabled - no environment variables needed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f 'Python Scripts/requirements.txt' ]; then pip install -r 'Python Scripts/requirements.txt'; fi
    - name: execute py script
      run: python 'Python Scripts/AMR_NewReleases_github.py'
    - name: commit and push files
      run: |
        git config --local user.email "mushroomoff@mail.ru"
        git config --local user.name "MushroomOFF"
        git add -A
        if ! git diff --cached --quiet; then
          git pull origin main --rebase || true
          git commit -m "daily AMR New Releases autoupdate $(date '+%Y-%m-%d %H:%M:%S')" || true
          git push origin main || true
        else
          echo "No changes to commit"
        fi 
