name: Apple Music New Releases

on:
  schedule:
    - cron: '9 5 * * 5'
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f 'Python Notebooks/requirements.txt' ]; then pip install -r 'Python Notebooks/requirements.txt'; fi
    - name: execute py script
      run: python 'Python Scripts/AMR_NewReleases_github.py'
    - name: commit files
      run: |
        git config --local user.email "mushroomoff@mail.ru"
        git config --local user.name "MushroomOFF"
        git commit -a -m "weekly AMR New Releases autoupdate"
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
